#####################################################
################# Spring properties #################
#####################################################
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimumIdle: 2
      idleTimeout: 120000
      maxLifetime: 900000
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/liquibase-changelog.xml
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE_INDEX}
  data:
    redis:
      repositories:
        enabled: false
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      pool:
        size: 3
      shutdown:
        await-termination: true
        await-termination-period: 30s

#####################################################
################# Server properties #################
#####################################################
server:
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful
